config/routes.rb
Rails.application.routes.draw do

  resources :productions

  match '/signin', :to => 'sessions#new', via: [:get]
  match '/signout', :to => 'sessions#destroy', via: [:get]
  match '/dashboard', to: 'dashboard#index', via: [:get]
  match '/stock', to: 'stock#index', via: [:get]
  match '/status', to: 'status#index', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:post]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:get]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:post]
  match '/diaries/stock', to: 'diaries#stock', via: [:get]
  match '/diaries/stock', to: 'diaries#stock', via: [:post]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:get]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:post]
  match '/invoices', to: 'invoices#purchases', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:post]
  match '/wear_outs/update', to: 'ehlak_osool#update', via: [:post]
  match '/income', to: 'income_menu#index', via: [:get]
  match '/income/:year', to: 'income_menu#index', via: [:get]
  match '/income/update', to: 'income_menu#update', via: [:patch]
  match '/financial_state', to: 'financial_state#index', via: [:get]
  match '/financial_state/:year', to: 'financial_state#index', via: [:get]
  match '/financial_state/update', to: 'financial_state#update', via: [:patch]
  match '/revision', to: 'revision#index', via: [:get]
  match '/revision/:year', to: 'revision#index', via: [:get]
  match '/revision/update', to: 'revision#update', via: [:patch]
  match '/clients/status', to: 'clients#status', via: [:post]
  match '/clients/:id', to: 'clients#show', via: [:post]
  match '/suppliers/:id', to: 'suppliers#show', via: [:post]
  match '/taxes', to: 'taxes#index', via: [:post]

  get '/dashboard/index'
  get '/clients/status'

  get 'dashboard/*a/*b', to: redirect('/%{a}/%{b}')
  get 'stock/index'
  match '/taxes', to: 'taxes#index', via: [:get]
  match '/taxes/:year', to: 'taxes#index', via: [:get]
  match '/taxes', to: 'taxes#index', via: [:post]

  get 'permission/production/:id', to: 'permission#production'
  get 'permission/product/:id', to: 'permission#product'
  get 'permission/material_stock/:id', to: 'permission#material_stock'
  get 'permission/material_expense/:id', to: 'permission#material_expense'
  get 'permission/material/:id1/:id2', to: 'permission#material'
  get 'permission/purchase/:id1/:id2', to: 'permission#purchase_with_invoice'
  get 'permission/purchase/:id', to: 'permission#purchase'
  get 'permission/expense/:id', to: 'permission#expense'
  
  get 'diaries/index', to: 'diaries#diaries'
  post 'diaries/index', to: 'diaries#diaries'

  get 'raw_materials/production'
  post 'raw_materials/permit'
  get 'raw_materials/permission'
  post 'materials/confirm'
  post 'purchases/confirm'

  get 'invoices/sales'
  get 'invoices/purchases'
  get 'permission/additions'
  get 'permission/subtractions'
  get 'permission/treasury'

  post 'expenses/confirm'
  get 'expenses/permission'
  get 'expenses/index'

  get 'purchases/invoice/:id', to: 'purchases#invoice'
  post 'materials/confirm'
  get 'materials/new_internal'
  get 'treasury/addtotreasury'
  get 'treasury/show'
  put 'treasury/update'

  get 'expense_payment_detail/:id', to: 'expense_payment_detail#edit'
  put 'expense_payment_detail/:id', to: 'expense_payment_detail#update'
  get 'purchase_payment_detail/:id', to: 'purchase_payment_detail#edit'
  put 'purchase_payment_detail/:id', to: 'purchase_payment_detail#update'
  get 'material_payment_detail/:id', to: 'material_payment_detail#edit'
  put 'material_payment_detail/:id', to: 'material_payment_detail#update'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users

  resources :treasury

  resources :suppliers

  resources :clients

  resources :purchases

  resources :expenses

  resources :products

  resources :materials
  resources :raw_materials
  resources :purchase_payment_detail
  resources :expense_payment_detail
  resources :material_payment_detail

   root 'sessions#new'

end

app/models/raw_material.rb
class RawMaterial < ActiveRecord::Base

	before_save :validate


	private
		def validate
			self.in_stock ||= 0
			self.deleted ||= 0
		end
end

app/controllers/raw_materials_controller.rb
class RawMaterialsController < ApplicationController
  before_action :set_raw_material, only: [:show, :edit, :update, :destroy, :permit]

  # GET /raw_materials
  # GET /raw_materials.json
  def index
    @raw_materials = RawMaterial.where.not(deleted: 1)
    super
  end

  # GET /raw_materials/1
  # GET /raw_materials/1.json
  def show
    super
  end

  # GET /raw_materials/new
  def new
    @raw_material = RawMaterial.new
    super
  end

  # GET /raw_materials/1/edit
  def edit
    super
  end

  # POST /raw_materials
  # POST /raw_materials.json
  def create
    @raw_material = RawMaterial.new(raw_material_params)
    @raw_material.in_stock = 0

    respond_to do |format|
      if @raw_material.save
        format.html { redirect_to raw_materials_url, notice: 'تم تسجيل المادة الخام بنجاح.' }
        format.json { render :show, status: :created, location: @raw_material }
      else
        format.html { render :new }
        format.json { render json: @raw_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raw_materials/1
  # PATCH/PUT /raw_materials/1.json
  def update
    respond_to do |format|
      if @raw_material.update(raw_material_params)
        format.html { redirect_to @raw_material, notice: 'تم تعديل المادة الخام بنجاح.' }
        format.json { render :show, status: :ok, location: @raw_material }
      else
        format.html { render :edit }
        format.json { render json: @raw_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raw_materials/1
  # DELETE /raw_materials/1.json
  def destroy
    @raw_material.update(deleted: 1)
    
    respond_to do |format|
      format.html { redirect_to raw_materials_url, notice: 'تم حذف المادة الخام بنجاح.' }
      format.json { head :no_content }
    end
  end

  def production
    @raw_materials = RawMaterial.all
    if request.xhr?
      render partial: 'production'
    else
      redirect_to "/dashboard##{request.path}"
    end
  end

  def permit
    if (@raw_material.in_stock >= params['quantity'].to_f)
      @raw_material.in_stock = @raw_material.in_stock - params['quantity'].to_f
      @raw_material.save
      production = Production.create!({raw_material_id: @raw_material.id, user_name: current_user.name, quantity:params['quantity'].to_f})
      permission = ProductionPermission.create!({transaction_id: production.id, quantity: params['quantity']})
      redirect_to "/permission/production/#{permission.id}"
    else
      redirect_to '/raw_materials/production', notice: "المتاح بالمخزن أقل من الكمية المطلوبة"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raw_material
      @raw_material = RawMaterial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raw_material_params
      params.require(:raw_material).permit(:name, :unit, :description, :in_stock, :deleted)
    end
end

app/helpers/raw_materials_helper.rb
module RawMaterialsHelper
end

app/views/raw_materials/_edit.html.erb
<%= render "layouts/ajaxify" %>

<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المواد الخام</li>
      <li>تعديل.مادة.خام</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>تعديل مادة خام</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@raw_material, html: {class: 'form-horizontal'}) do |f| %>
            <% if @raw_material.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@raw_material.errors.count, "error") %> prohibited this raw_material from being saved:</h2>

                <ul>
                <% @raw_material.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :name,  'اسم المادة الخام', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", placeholder:"اسم المادة الخام", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"اسم المادة الخام"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :description,  'الوصف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_area :description , {class:"form-control", placeholder:"الوصف"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :unit,  'الوحدة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :unit , {class:"form-control", placeholder:"مثال: كجم", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"الوحدة"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :in_stock,  'الكمية', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :in_stock , {class:"form-control", placeholder:"رقم", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"رقم"}%>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2 pull-right">
                <%= f.submit "تعديل المادة الخام", class:"btn btn-primary btn-label-left" %>
              </div>
              <div class="col-sm-offset-1 col-sm-2 pull-right">
                <button type="cancel" class="btn btn-default btn-label-left">
                <span><i class="fa fa-clock-o txt-danger"></i></span>
                  إلغاء
                </button>
            </div>
          </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}

function validator() {
    $('form').bootstrapValidator({
    message: 'برجاء مراجعة المدخل',
    fields: {
      'raw_material[name]': {
        message: 'الاسم غير مقبول',
        validators: {
          notEmpty: {
            message: 'الاسم مطلوب'
          },
          stringLength: {
            min: 3,
            max: 30,
            message: 'الاسم من 3 إلى 30 حرف'
          }
        }
      },
      'raw_material[unit]': {
        validators: {
          notEmpty: {
            message: 'لابد من إدخال الوحدة'
          }
        }
      },
      'raw_material[unit]': {
        validators: {
          notEmpty: {
            message: 'لابد من إدخال الوحدة'
          },
          numeric: {
            message: 'أرقام فقط'
          }
        }
      }
    }
  });
}

$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(validator);
  // Add drag-n-drop feature to boxes
  WinMove();
  // $('button[type=cancel],select').attr('onclick', 'window.location.href = "/"; return false;')
});
</script>

app/views/raw_materials/_form.html.erb
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المواد الخام</li>
      <li>تسجيل مادة خام</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>بيانات المادة الخام</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@raw_material, html: {class: 'form-horizontal'}) do |f| %>
            <% if @raw_material.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@raw_material.errors.count, "error") %> prohibited this raw_material from being saved:</h2>

                <ul>
                <% @raw_material.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :name,  'اسم المادة الخام', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", placeholder:"اسم المادة الخام", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"اسم المادة الخام"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :description,  'الوصف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_area :description , {class:"form-control", placeholder:"الوصف"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :unit,  'الوحدة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :unit , {class:"form-control", placeholder:"مثال: كجم", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"الوحدة"}%>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2 pull-right">
                <%= f.submit "تسجيل المادة الخام", class:"btn btn-primary btn-label-left" %>
              </div>
              <div class="col-sm-offset-1 col-sm-2 pull-right">
                <button type="cancel" class="btn btn-default btn-label-left">
                <span><i class="fa fa-clock-o txt-danger"></i></span>
                  إلغاء
                </button>
            </div>
          </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
function validator() {
    $('form').bootstrapValidator({
    message: 'برجاء مراجعة المدخل',
    fields: {
      'raw_material[name]': {
        message: 'الاسم غير مقبول',
        validators: {
          notEmpty: {
            message: 'الاسم مطلوب'
          },
          stringLength: {
            min: 3,
            max: 30,
            message: 'الاسم من 3 إلى 30 حرف'
          }
        }
      },
      'raw_material[unit]': {
        validators: {
          notEmpty: {
            message: 'لابد من إدخال الوحدة'
          }
        }
      }
    }
  });
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(validator);
  // Add drag-n-drop feature to boxes
  WinMove();
  // $('button[type=cancel],select').attr('onclick', 'window.location.href = "/"; return false;')
});
</script>

app/views/raw_materials/_index.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرسمية</li>
      <li>المواد الخام</li>
      <li>عرض المواد الخام</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-linux"></i>
          <span>عرض المواد الخام</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content no-padding table-responsive">
        <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-2">
          <thead>
            <tr>
              <th>الاسم</th>
              <th>الوحدة</th>
              <th>المخزون</th>
            </tr>
          </thead>
          <tbody>
            <% @raw_materials.each do |raw_material| %>
              <tr data-href="<%= raw_material_path(raw_material) %>">
                <td><%= raw_material.name %></td>
                <td><%= raw_material.unit %></td>
                <td><%= raw_material.in_stock %></td>
              </tr>
            <% end %>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <th><label><input type="text" name="search_name" value="البحث بالاسم" class="search_init" /></label></th>
              <th><label><input type="text" name="search_unit" value="البحث بالوحدة" class="search_init" /></label></th>
              <th><label><input type="text" name="search_state" value="البحث بالمخزون" class="search_init" /></label></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
  setupTables();
  LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
  $('select').select2();
  $('.dataTables_filter').each(function(){
    $(this).find('label input[type=text]').attr('placeholder', 'Search');
  });
}
$(document).ready(function() {
  // Load Datatables and run plugin on tables 
  LoadDataTablesScripts(AllTables);
  // Add Drag-n-Drop feature
  WinMove();
  $("tr[data-href]").click(function() {
  window.location = this.dataset.href;
}).hover(function() {
    $(this).toggleClass('hover');
});
});
</script>

app/views/raw_materials/_new.html.erb
<%= render 'form' %>

<%= link_to 'Back', raw_materials_path %>

app/views/raw_materials/_permission.html.erb
<div class="row">
	<div id="breadcrumb" class="col-md-12">
		<ol class="breadcrumb">
			<li>الصفحة الرئيسية</li>
			<li>عمليات البيع</li>
			<li>اذن.تصنيع</li>
		</ol>
	</div>
</div>
<div class="row"  dir="ltr">
	<div class="col-xs-8 col-xs-offset-2" id="invoice">
		<div class="box">
			<div class="box-content">
				<div class="col-xs-6">
					<address>
						<strong>Alexink Egypt</strong><br>
						6 Aziz Fahmy St. Sporting, Alexandria, <br>
						Alexandria<br>
						Egypt <br>
						<abbr title="Phone">P:</abbr> (+2) 03-5469692
					</address>
					<address>
						<strong>Email</strong><br>
						<a href="mailto:#">info@alexinkegypt.net</a>
					</address>
				</div>
				<div class="col-xs-6 well text-center">
					إذن خصم من المخزن للصناعة
				</div>
				<div class="col-xs-6 well text-center">
					اذن رقم <%= @permission_num%>
				</div>
				<div class="col-xs-6 well text-center">
					التاريخ <%= Time.now.strftime("%m/%d/%Y") %>
				</div>
				<div class="clearfix"></div>
				<div class="col-xs-12">
					<strong class="well col-xs-12" style="text-align: center;">المادة الخام: <%= @raw_material.name%></strong>
					<strong class="well col-xs-6" style="text-align: center;">الباقي بالمخزن: <%= @raw_material.in_stock - @permission.quantity.to_i%></strong><br/><br/>
					<strong class="well col-xs-6" style="text-align: center;">الكمية: <%= @permission.quantity%></strong>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
</div>
<div class="col-xs-6 col-xs-offset-6">
					<div class="col-xs-4">
						<a href"" class="btn btn-default btn-label-left" id="print"><span><i class="fa fa-floppy-o"></i></span> طباعة وحفظ</a>
					</div>
				</div>

<%= javascript_include_tag 'js/jspdf.min' %>
<%= javascript_include_tag 'js/html2canvas' %>
<script>
	//require 'jspdf'
	var doc = new jsPDF('p', 'pt', 'a4');
	var specialElementHandlers = {
	    '#editor': function (element, renderer) {
	        return true;
	    }
	};
	$('#print').click(function () {
		html2canvas(document.querySelector("#invoice"), { onrendered: function(canvas) {
			console.log(canvas.toDataURL());
			doc.addImage(canvas.toDataURL(), 'JPEG', 10, 10, 210, 297);
    		doc.save('sample-file.pdf');
		}});
		$.ajax({ url: '/raw_materials/confirm',
		  type: 'POST',
		  beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
		  success: function(response) {
		  	window.location = "/raw_materials"
		  }
		});
	    
	});

</script>

app/views/raw_materials/_show.html.erb
<%= render "layouts/ajaxify" %>

<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المواد الخام</li>
      <li>عرض.مادة.خام</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>عرض.مادة.خام</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@raw_material, html: {class: 'form-horizontal'}) do |f| %>
            <% if @raw_material.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@raw_material.errors.count, "error") %> prohibited this raw_material from being saved:</h2>

                <ul>
                <% @raw_material.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :name,  'اسم المادة الخام', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :description,  'الوصف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_area :description , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :unit,  'الوحدة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :unit , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :in_stock,  'الكمية', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :in_stock , {class:"form-control", disabled:true}%>
              </div>
            </div>
            <%= link_to 'تعديل', edit_raw_material_path(@raw_material) %>
            <%= link_to 'حذف', @raw_material, method: :delete, data: { confirm: 'هل أنت متأكد؟' } %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(DemoFormValidator);
  // Add drag-n-drop feature to boxes
  WinMove();
});
</script>