config/routes.rb
Rails.application.routes.draw do

  resources :productions

  match '/signin', :to => 'sessions#new', via: [:get]
  match '/signout', :to => 'sessions#destroy', via: [:get]
  match '/dashboard', to: 'dashboard#index', via: [:get]
  match '/stock', to: 'stock#index', via: [:get]
  match '/status', to: 'status#index', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:post]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:get]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:post]
  match '/diaries/stock', to: 'diaries#stock', via: [:get]
  match '/diaries/stock', to: 'diaries#stock', via: [:post]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:get]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:post]
  match '/invoices', to: 'invoices#purchases', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:post]
  match '/wear_outs/update', to: 'ehlak_osool#update', via: [:post]
  match '/income', to: 'income_menu#index', via: [:get]
  match '/income/:year', to: 'income_menu#index', via: [:get]
  match '/income/update', to: 'income_menu#update', via: [:patch]
  match '/financial_state', to: 'financial_state#index', via: [:get]
  match '/financial_state/:year', to: 'financial_state#index', via: [:get]
  match '/financial_state/update', to: 'financial_state#update', via: [:patch]
  match '/revision', to: 'revision#index', via: [:get]
  match '/revision/:year', to: 'revision#index', via: [:get]
  match '/revision/update', to: 'revision#update', via: [:patch]
  match '/clients/status', to: 'clients#status', via: [:post]
  match '/clients/:id', to: 'clients#show', via: [:post]
  match '/suppliers/:id', to: 'suppliers#show', via: [:post]
  match '/taxes', to: 'taxes#index', via: [:post]

  get '/dashboard/index'
  get '/clients/status'

  get 'dashboard/*a/*b', to: redirect('/%{a}/%{b}')
  get 'stock/index'
  match '/taxes', to: 'taxes#index', via: [:get]
  match '/taxes/:year', to: 'taxes#index', via: [:get]
  match '/taxes', to: 'taxes#index', via: [:post]

  get 'permission/production/:id', to: 'permission#production'
  get 'permission/product/:id', to: 'permission#product'
  get 'permission/material_stock/:id', to: 'permission#material_stock'
  get 'permission/material_expense/:id', to: 'permission#material_expense'
  get 'permission/material/:id1/:id2', to: 'permission#material'
  get 'permission/purchase/:id1/:id2', to: 'permission#purchase_with_invoice'
  get 'permission/purchase/:id', to: 'permission#purchase'
  get 'permission/expense/:id', to: 'permission#expense'
  
  get 'diaries/index', to: 'diaries#diaries'
  post 'diaries/index', to: 'diaries#diaries'

  get 'raw_materials/production'
  post 'raw_materials/permit'
  get 'raw_materials/permission'
  post 'materials/confirm'
  post 'purchases/confirm'

  get 'invoices/sales'
  get 'invoices/purchases'
  get 'permission/additions'
  get 'permission/subtractions'
  get 'permission/treasury'

  post 'expenses/confirm'
  get 'expenses/permission'
  get 'expenses/index'

  get 'purchases/invoice/:id', to: 'purchases#invoice'
  post 'materials/confirm'
  get 'materials/new_internal'
  get 'treasury/addtotreasury'
  get 'treasury/show'
  put 'treasury/update'

  get 'expense_payment_detail/:id', to: 'expense_payment_detail#edit'
  put 'expense_payment_detail/:id', to: 'expense_payment_detail#update'
  get 'purchase_payment_detail/:id', to: 'purchase_payment_detail#edit'
  put 'purchase_payment_detail/:id', to: 'purchase_payment_detail#update'
  get 'material_payment_detail/:id', to: 'material_payment_detail#edit'
  put 'material_payment_detail/:id', to: 'material_payment_detail#update'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users

  resources :treasury

  resources :suppliers

  resources :clients

  resources :purchases

  resources :expenses

  resources :products

  resources :materials
  resources :raw_materials
  resources :purchase_payment_detail
  resources :expense_payment_detail
  resources :material_payment_detail

   root 'sessions#new'

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
    @clients = Client.all
    @products = Product.all
    super
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @clients = Client.all
    @products = Product.all
    super
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
    @clients = Client.where.not(deleted: 1)
    @products = Product.where.not(deleted: 1)
    super
  end

  # GET /purchases/1/edit
  def edit
    @clients = Client.all
    @products = Product.all
    super
  end

  # POST /purchases
  # POST /purchases.json

  def create
    _params = purchase_params
    if validate_params(_params) then
      purchase = Purchase.new(_params)
      purchase.user_name = current_user.name
      products = []
      ids = _params['product_ids']
      product_num = ids.length
      product_num.times do |i|
        product = Product.find(ids[i])
        puts _params['quantities'][i].to_f
        puts product.in_stock 
        if (product.in_stock < _params['quantities'][i].to_f)
          redirect_to '/purchases/new', notice: 'الكمية المتاحة بالمخزن من ذلك المنتج أقل من المطلوب'
          return
        end
        products.push product
      end
      purchase.price = 0
      purchase.prices.each_with_index do |price, i|
        purchase.price = purchase.price + price.to_f * purchase.quantities[i].to_f
      end
      if _params['paid_amount'].present? && purchase.price < _params['paid_amount'].to_f
        redirect_to '/purchases/new', notice: 'لا يمكن أن يكون المبلغ المدفوع أكبر من السعر الكلي'
        return
      end
      if (purchase.payment_state == "آجل")
        purchase.debt = purchase.price_with_taxes - params["paid_amount"].to_f
      else
        purchase.debt = 0
      end
      if purchase.save
         invoice = Invoice.create!({purchase_id: purchase.id})
         permission = ReleaseProductPermission.create!({transaction_id: purchase.id})
         purchase.invoice_id = invoice.id
         purchase.save
         if (purchase.price_with_taxes != purchase.debt)
            update_treasury(purchase.payment_method, purchase.price_with_taxes - purchase.debt, PURCHASE, purchase.id, "عملية بيع", 0, params["cheque_num"], purchase.date_added)
         end
         # if purchase.debt == 0
         #  add_tax(purchase.payment_method, PURCHASE, purchase.id, purchase.price)
         # end
         # treasury = Treasury.first
         # if (purchase.payment_method == "cash")
         #  treasury.cash = treasury.cash + purchase.price - purchase.debt
         # else
         #  treasury.bank = treasury.bank + purchase.price - purchase.debt
         # end
         client = Client.find(purchase.client_id)
         client.debt = client.debt + purchase.debt
         products.each_with_index do |product, i|
          product.in_stock = product.in_stock - purchase.quantities[i].to_f
          product.save
         end

         # treasury.save
         client.save
         PurchasePaymentDetail.create()

         redirect_to "/permission/purchase/#{permission.id}/#{invoice.id}"
      end
    else
      redirect_to '/purchases/new', notice: 'حدث خطأ في معالجة الطلب. برجاء مراجعة المدخلات'
    end
  end

  def invoice
    @invoice = Invoice.find(params[:id])
    @purchase = Purchase.find(@invoice.purchase_id)
    @client = Client.find(@purchase.client_id)
    @products = Product.find(@purchase.product_ids)
    super
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    debt = @purchase.debt
    p = purchase_params
    p['product_ids'] = @purchase.product_ids
    respond_to do |format|
      if @purchase.update(p)
        if (debt != @purchase.debt)
          update_treasury(@purchase.payment_method, debt - @purchase.debt, PURCHASE, @purchase.id, "تعديل موقف عملية بيع", 0, params["cheque_num"])
        end
        # if debt > 0 && @purchase.debt == 0
        #   add_tax(@purchase.payment_method, PURCHASE, @purchase.id, @purchase.price)
        # end
        # treasury = Treasury.first
        # if (params['payment_method'] == "cash")
        #   treasury.cash = treasury.cash + (@purchase.debt - purchase_params[:debt].to_f)
        # else
        #   treasury.bank = treasury.bank + (@purchase.debt - purchase_params[:debt].to_f)
        # end
        # treasury.save
        client = Client.find(@purchase.client_id)
        client.debt = client.debt - (debt - purchase_params[:debt].to_f)
        client.save

        format.html { redirect_to purchases_url, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    permissions = ReleaseProductPermission.where(transaction_id: @purchase.id)
    p = PurchasePaymentDetail.find_by_id(@purchase.id)
    if p
      p.destroy
    end
    Invoice.delete(@purchase.id)
    update_treasury(@purchase.payment_method, -@purchase.price_with_taxes, PURCHASE, @purchase.id, "مسح حركة بيع", 0)
    TreasuryDiary.where(transaction_id: @purchase.id, transaction_type: PURCHASE).destroy_all
    permissions.destroy_all
    client = Client.find(@purchase.client_id)
    new_debt = client.debt - @purchase.debt
    client.update(debt: new_debt)
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'تم مسح عملية البيع.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      _params = params.require(:purchase).permit(:date_added, :payment_method, :calc_sub_tax,
       :payment_state, :client_id, :payment_method, :payment_state, :state, :debt,
        :quantities => [], :prices => [], )
      _params[:product_ids] = params[:product_ids]
      return _params
    end

    def validate_params(params)  
      params[:prices].each do |price|
        if !is_float?(price)
          return nil
        elsif price.to_f < 0
          return nil
        end
      end
      params[:quantities].each do |quantity|
        if !is_float?(quantity)
          return nil
        elsif quantity.to_f < 0
          return nil
        end
      end
      return true
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_index.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المبيعات</li>
      <li>عرض عمليات البيع</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-linux"></i>
          <span>عرض جميع عمليات البيع</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content no-padding table-responsive">
        <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-2">
          <thead>
            <tr>
              <th>التاريخ</th>
              <th>المنتجات</th>
              <th>العميل</th>
              <th>المبلغ</th>
              <th>الموقف</th>
              <th>العملة</th>
              
            </tr>
          </thead>
          <tbody>
            <% @purchases.each do |purchase| %>
              <tr data-href="<%= purchase_path(purchase) %>">
                <td><%= purchase.date_added %></td>
                <td>
                  <ul>
                    <% Product.find(purchase.product_ids).each do |r| %>
                    <li><%= r.name%></li>
                    <%end%>
                  </ul>
                </td>
                <td><%= @clients.find(purchase.client_id).name %></td>
                <td><%= purchase.price_with_taxes %></td>
                <td><%= purchase.debt %></td>
                <td><%= purchase.currency %></td>
                
              </tr>
            <% end %>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <th><label><input type="text" name="search_date" value="البحث بالتاريخ" class="search_init" /></label></th>
              <th><label><input type="text" name="search_name" value="البحث بالعميل" class="search_init" /></label></th>
              <th><label><input type="text" name="search_ppunit" value="البحث بالسعر" class="search_init" /></label></th>
              <th><label><input type="text" name="search_currency" value="البحث بالعملة" class="search_init" /></label></th>
              <th><label><input type="text" name="search_debt" value="البحث بالموقف" class="search_init" /></label></th>
              <th><label><input type="text" name="search_currency" value="البح بالعملة" class="search_init" /></label></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
  setupTables();
  LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
  $('select').select2();
  $('.dataTables_filter').each(function(){
    $(this).find('label input[type=text]').attr('placeholder', 'Search');
  });
}
$(document).ready(function() {
  // Load Datatables and run plugin on tables 
  LoadDataTablesScripts(AllTables);
  // Add Drag-n-Drop feature
  WinMove();
    $("tr[data-href]").click(function() {
  window.location = this.dataset.href;
}).hover(function() {
    $(this).toggleClass('hover');
});
});
</script>

app/views/purchases/_new.html.erb
<%= render "layouts/ajaxify" %>
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/_show.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">الصفحة الؤئيسية</a></li>
      <li>المبيعات</li>
      <li>عرض.عملية.بيع</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>عرض عملية بيع</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
          <%= form_for(@purchase, html: {class: 'form-horizontal'}) do |f| %>
            <% if @purchase.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

                <ul>
                <% @purchase.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= label_tag 'date',  'التاريخ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'date', @purchase.date_added, {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= label_tag 'employee',  'الموظف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'user_name', @purchase.user_name, {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :client_id,  'العميل', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.select :client_id, @clients.collect {|c| [c.name, c.id]}, {}, {class:"pull-right",style:"min-width:100%", disabled:true} %>
              </div>
            </div>

            <div id="products">
              <%@purchase.product_ids.each_with_index do |p, i|%>
                <div id="product" style="border: 1px solid #000; border-radius:10px;">
                  <div class="form-group">
                    <%= f.label :product_ids,  'المنتج', {class:"col-sm-2 control-label pull-right"}%>
                    <div class="col-sm-4 pull-right">
                      <%= text_field_tag "product_ids[]", @products.find(p).name, {class:"form-control", disabled:true}%>
                    </div>
                  </div>

                  <div class="form-group">
                    <%= f.label :quantities,  'الكمية', {class:"col-sm-2 control-label pull-right"}%>
                    <div class="col-sm-4 pull-right">
                      <%= text_field_tag "quantities" , @purchase.quantities[i], {class:"form-control", disabled:true}%>
                      
                    </div>
                  </div>

                  <div class="form-group">
                    <%= f.label :prices,  'سعر الوحدة', {class:"col-sm-2 control-label pull-right"}%>
                    <div class="col-sm-4 pull-right">
                      <%= text_field_tag "prices" , @purchase.prices[i], {class:"form-control", disabled:true}%>
                    </div>
                  </div>
                </div>
              <%end%>
            </div>

            <div class="form-group">
              <%= f.label :payment_method,  'طريقة الدفع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :payment_method, {class:"form-control pull-right", disabled:true} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :payment_state,  'حالة الدفع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :payment_state, {class:"form-control pull-right", disabled:true} %>
              </div>
            </div>
            <div  class="form-group">
                <%= f.label :debt,  'المبلغ المتبقي', {class:"col-sm-2 control-label pull-right"}%>
                <div class="col-sm-4 pull-right">
                  <%= f.text_field :debt , {class:"form-control", disabled:true}%>
                </div>
            </div>

            <%if @purchase.debt > 0%>
              <div class="form-group">
                <%= f.label :due_date,  'تاريخ الاستحقاق', {class:"col-sm-2 control-label pull-right"}%>
                <div class="col-sm-2 pull-right">
                  <%= f.text_field :due_date , {class:"form-control", disabled:true}%>
                </div>
              </div>
            <%end%>

          <%= link_to 'تعديل', edit_purchase_path(@purchase)%> |
          <%= link_to 'حذف', @purchase, method: :delete, data: { confirm: 'هل أنت متأكد؟' } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(DemoFormValidator);
  // Add drag-n-drop feature to boxes
  WinMove();

});

</script>

app/views/purchases/_show2.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/">الصفحة الؤئيسية</a></li>
      <li>المبيعات</li>
      <li>عرض.عملية.بيع</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>عرض عملية بيع</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@purchase, html: {class: 'form-horizontal'}) do |f| %>
            <% if @purchase.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

                <ul>
                <% @purchase.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= label_tag 'date',  'التاريخ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'date', @purchase.created_at.strftime("%Y/%m/%d"), {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= label_tag 'employee',  'الموظف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'user_name', @purchase.user_name, {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :product_id,  'المنتج', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.select :product_id, @products.collect {|p| [p.name, p.id]}, {}, {class:"pull-right", style:"min-width:100%", disabled:true} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :client_id,  'العميل', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.select :client_id, @clients.collect {|c| [c.name, c.id]}, {}, {class:"pull-right",style:"min-width:100%", disabled:true} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :quantity,  'الكميلة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :quantity , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :price,  'المبلغ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :price , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :payment_method,  'طريقة الدفع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :payment_method, {class:"pull-right", disabled:true} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :payment_state,  'حالة الدفع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :payment_state, {class:"pull-right", disabled:true} %>
              </div>
            </div>
            <div  class="form-group">
                <%= f.label :debt,  'المبلغ المتبقي', {class:"col-sm-2 control-label pull-right"}%>
                <div class="col-sm-4 pull-right">
                  <%= f.text_field :debt , {class:"form-control", disabled:true}%>
                </div>
            </div>
            <%= hidden_field_tag 'purchase_id', @purchase.id%>
            <div class="col-xs-6 col-xs-offset-6">
              <div class="col-xs-4">
                <%= link_to 'طباعة الفاتورة', "/purchases/print_invoice/#{@purchase.id}", class:"btn btn-default btn-label-left"%>
              </div>
            </div>

          <%= link_to 'تعديل', edit_purchase_path(@purchase)%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(DemoFormValidator);
  // Add drag-n-drop feature to boxes
  WinMove();

});

</script>