config/routes.rb
Rails.application.routes.draw do

  resources :productions

  match '/signin', :to => 'sessions#new', via: [:get]
  match '/signout', :to => 'sessions#destroy', via: [:get]
  match '/dashboard', to: 'dashboard#index', via: [:get]
  match '/stock', to: 'stock#index', via: [:get]
  match '/status', to: 'status#index', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:post]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:get]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:post]
  match '/diaries/stock', to: 'diaries#stock', via: [:get]
  match '/diaries/stock', to: 'diaries#stock', via: [:post]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:get]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:post]
  match '/invoices', to: 'invoices#purchases', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:post]
  match '/wear_outs/update', to: 'ehlak_osool#update', via: [:post]
  match '/income', to: 'income_menu#index', via: [:get]
  match '/income/:year', to: 'income_menu#index', via: [:get]
  match '/income/update', to: 'income_menu#update', via: [:patch]
  match '/financial_state', to: 'financial_state#index', via: [:get]
  match '/financial_state/:year', to: 'financial_state#index', via: [:get]
  match '/financial_state/update', to: 'financial_state#update', via: [:patch]
  match '/revision', to: 'revision#index', via: [:get]
  match '/revision/:year', to: 'revision#index', via: [:get]
  match '/revision/update', to: 'revision#update', via: [:patch]
  match '/clients/status', to: 'clients#status', via: [:post]
  match '/clients/:id', to: 'clients#show', via: [:post]
  match '/suppliers/:id', to: 'suppliers#show', via: [:post]
  match '/taxes', to: 'taxes#index', via: [:post]

  get '/dashboard/index'
  get '/clients/status'

  get 'dashboard/*a/*b', to: redirect('/%{a}/%{b}')
  get 'stock/index'
  match '/taxes', to: 'taxes#index', via: [:get]
  match '/taxes/:year', to: 'taxes#index', via: [:get]
  match '/taxes', to: 'taxes#index', via: [:post]

  get 'permission/production/:id', to: 'permission#production'
  get 'permission/product/:id', to: 'permission#product'
  get 'permission/material_stock/:id', to: 'permission#material_stock'
  get 'permission/material_expense/:id', to: 'permission#material_expense'
  get 'permission/material/:id1/:id2', to: 'permission#material'
  get 'permission/purchase/:id1/:id2', to: 'permission#purchase_with_invoice'
  get 'permission/purchase/:id', to: 'permission#purchase'
  get 'permission/expense/:id', to: 'permission#expense'
  
  get 'diaries/index', to: 'diaries#diaries'
  post 'diaries/index', to: 'diaries#diaries'

  get 'raw_materials/production'
  post 'raw_materials/permit'
  get 'raw_materials/permission'
  post 'materials/confirm'
  post 'purchases/confirm'

  get 'invoices/sales'
  get 'invoices/purchases'
  get 'permission/additions'
  get 'permission/subtractions'
  get 'permission/treasury'

  post 'expenses/confirm'
  get 'expenses/permission'
  get 'expenses/index'

  get 'purchases/invoice/:id', to: 'purchases#invoice'
  post 'materials/confirm'
  get 'materials/new_internal'
  get 'treasury/addtotreasury'
  get 'treasury/show'
  put 'treasury/update'

  get 'expense_payment_detail/:id', to: 'expense_payment_detail#edit'
  put 'expense_payment_detail/:id', to: 'expense_payment_detail#update'
  get 'purchase_payment_detail/:id', to: 'purchase_payment_detail#edit'
  put 'purchase_payment_detail/:id', to: 'purchase_payment_detail#update'
  get 'material_payment_detail/:id', to: 'material_payment_detail#edit'
  put 'material_payment_detail/:id', to: 'material_payment_detail#update'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users

  resources :treasury

  resources :suppliers

  resources :clients

  resources :purchases

  resources :expenses

  resources :products

  resources :materials
  resources :raw_materials
  resources :purchase_payment_detail
  resources :expense_payment_detail
  resources :material_payment_detail

   root 'sessions#new'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  GENERAL = 0
  PRODUCTION = 1

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
    super
    flash.discard(:notice)
  end

  def index_general
    @expenses = Expense.where(e_type: GENERAL)
    if request.xhr?
      flash.discard(:notice)
      render partial: 'index'
    else
      redirect_to "/dashboard##{request.path}"
    end
    flash.discard(:notice)
  end

  def index_production
    @expenses = Expense.where(e_type: PRODUCTION)
    if request.xhr?
      flash.discard(:notice)
      render partial: 'index'
    else
      redirect_to "/dashboard##{request.path}"
    end
    flash.discard(:notice)
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    super
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    super
  end

  # GET /expenses/1/edit
  def edit
    super
  end

  # POST /expenses
  # POST /expenses.json

  def create
    if validate_params(expense_params) then
      treasury = Treasury.first
      if (expense_params['payment_method'] == "cash")
        if (treasury.cash < (expense_params['price'].to_f))
          redirect_to "/expenses/new", notice: 'المبلغ الموجود بالخزنة أقل من المبلغ المطلوب'
          return
        end
      elsif (treasury.bank < (expense_params['price'].to_f))
        redirect_to "/expenses/new", notice: 'المبلغ الموجود بالبنك أقل من المبلغ المطلوب'
        return
      end
      @expense = Expense.new(expense_params)
      @expense.user_name = current_user.name

      if @expense.save
        permission = ReleaseMoneyPermission.create!({transaction_for: EXPENSE, transaction_id: @expense.id, quantity: @expense.price})
        ExpensePaymentDetail.create()
        update_treasury(@expense.payment_method, - @expense.price, EXPENSE, @expense.id, "مصروفات مباشرة", 0, @expense.date_added)
        redirect_to "/permission/expense/#{permission.id}"
      else
        redirect_to "/expenses/new", notice: 'تعذر تسجيل عملية الصرف. برجاء مراجعة المدخلات'  
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expenses_url, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    permissions = ReleaseMoneyPermission.where(transaction_for: EXPENSE, transaction_id: @expense.id)
    permissions.destroy_all
    update_treasury(@expense.payment_method, @expense.price, EXPENSE, @expense.id, "مسح حركة بيع", 0)
    TreasuryDiary.where(transaction_id: @expense.id, transaction_type: EXPENSE).destroy_all
    e = ExpensePaymentDetail.find_by_id(@expense.id)
    if e
      e.destroy
    end
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:name, :price, :seller, :payment_method, :payment_state, :debt, :e_type, :date_added)
    end

    def validate_params(params)
      if params[:name].present? && params[:seller].present? && params[:price].present? then
        return is_float?(params[:price])
      end
      return nil
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_edit.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المصروفات</li>
      <li>تعديل مصروفات جديدة</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>تفاصيل المصروفات</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@expense, html: {class: 'form-horizontal'}) do |f| %>
            <% if @expense.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

                <ul>
                <% @expense.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= label_tag 'date',  'التاريخ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'date', @expense.created_at.strftime("%Y/%m/%d"), {class:"form-control", disabled:true}%>
              </div>
            </div>
            
            <div class="form-group">
              <%= label_tag 'employee',  'الموظف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'user_name', @expense.user_name, {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :name,  'وصف المصروفات', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :seller,  'المستحق', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :seller , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :price,  'المبلغ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :price , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :e_type,  'النوع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.select :e_type, [['مصروفات عمومية', 0], ['مصروفات تشغيلية', 1]], {}, {class:"pull-right", style:"min-width:100%"} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :payment_method,  'طريقة الدفع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :payment_method, {class:"pull-right", disabled:true} %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2 pull-right">
                <%= f.submit "تعديل البيانات", class:"btn btn-primary btn-label-left" %>
              </div>
              <div class="col-sm-offset-1 col-sm-2 pull-right">
                <button type="cancel" class="btn btn-default btn-label-left">
                <span><i class="fa fa-clock-o txt-danger"></i></span>
                  إلغاء
                </button>
            </div>
            </div>
          </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(DemoFormValidator);
  // Add drag-n-drop feature to boxes
  WinMove();
  // $('button[type=cancel],select').attr('onclick', 'window.location.href = "/"; return false;')
});
</script>

app/views/expenses/_form.html.erb
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المصروفات</li>
      <li>ادخال مصروفات جديدة</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>تفاصيل المصروفات</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@expense, html: {class: 'form-horizontal'}) do |f| %>
            <% if @expense.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

                <ul>
                <% @expense.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            
            <div class="form-group">
              <%= f.label :date_added,  'تاريخ الحركة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-3 pull-right">
                  <%= f.date_field :date_added, {class:"form-control"}%>
              </div>
            </div>
            
            <div class="form-group">
              <%= f.label :name,  'وصف المصروفات', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", placeholder:"وصف المصروفات", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"وصف المصروفات"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :seller,  'المستحق', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :seller , {class:"form-control", placeholder:"المستحق", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"المستحق"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :price,  'المبلغ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :price , {class:"form-control", placeholder:"المبلغ", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"المبلغ"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :e_type,  'النوع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.select :e_type, [['مصروفات عمومية', 0], ['مصروفات تشغيلية', 1], ['مصروفات بيعية', 2]], {}, {class:"pull-right", style:"min-width:100%"} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :payment_method,  'طريقة الدفع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.select :payment_method, ['cash', 'bank'], {}, {class:"pull-right", style:"min-width:100%"} %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2 pull-right">
                <%= f.submit "إدخال المصروفات", class:"btn btn-primary btn-label-left" %>
              </div>
              <div class="col-sm-offset-1 col-sm-2 pull-right">
                <button type="cancel" class="btn btn-default btn-label-left">
                <span><i class="fa fa-clock-o txt-danger"></i></span>
                  إلغاء
                </button>
            </div>
          </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}

function validator() {
    $('#new_expense').bootstrapValidator({
    message: 'برجاء مراجعة المدخل',
    fields: {
      'expense[name]': {
        message: 'الاسم مطلوب',
        validators: {
          notEmpty: {
            message: 'الاسم مطلوب'
          },
          stringLength: {
            min: 3,
            max: 30,
            message: 'الاسم من 3 إلى 30 حرف'
          }
        }
      },
      'expense[seller]': {
        validators: {
          notEmpty: {
            message: 'لا يمكن أن يكون المستحق فارغاً'
          }
        }
      },
      'expense[price]': {
        validators: {
          notEmpty: {
            message: 'المبلغ مطلوب'
          },
          numeric: {
            message: 'اأرقام فقط'
          }
        }
      }
    }
  });
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  document.getElementById('expense_date_added').valueAsDate = new Date();
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(validator);
  // Add drag-n-drop feature to boxes
  WinMove();

  // $('button[type=cancel],select').attr('onclick', 'window.location.href = "/"; return false;')
});

function set_debt() {
  $('#expense_debt').val(0)
  if ($('#expense_payment_state').val() == "آجل") {
    $('#debt-div').show();
  }
  else {
   $('#debt-div').hide();
  }
}
</script>

app/views/expenses/_index.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>Alexink Egypt</li>
      <li>المصروفات</li>
      <li>عرض المصروفات</li>
    </ol>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-linux"></i>
          <span>عرض جميع المصروفات</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content no-padding table-responsive">
        <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-2">
          <thead>
            <tr>
              <th>التاريخ</th>
              <th>الاسم</th>
              <th>المستحق</th>
              <th>النوع</th>
              <th>المبلغ</th>
            </tr>
          </thead>
          <tbody>
            <% @expenses.each do |expense| %>
              <tr data-href="<%= expense_path(expense) %>">
                <td><%= expense.date_added %></td>
                <td><%= expense.name %></td>
                <td><%= expense.seller %></td>
                <td><%= expense.e_type == 2 ? 'مصروفات بيعية' : (expense.e_type == 1 ? 'مصروفات تشغيلية' : 'مصروفات عمومية')%></td>
                <td><%= expense.price %></td>
              </tr>
            <% end %>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <th><label><input type="text" name="search_date" value="البحث بالتاريخ" class="search_init" /></label></th>
              <th><label><input type="text" name="search_name" value="البحث بالاسم" class="search_init" /></label></th>
              <th><label><input type="text" name="search_seller" value="البحث بالمستحق" class="search_init" /></label></th>
              <th><label><input type="text" name="search_seller" value="البحث بالنوع" class="search_init" /></label></th>
              <th><label><input type="text" name="search_price" value="البحث بالمبلغ" class="search_init" /></label></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
  setupTables();
  LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
  $('select').select2();
  $('.dataTables_filter').each(function(){
    $(this).find('label input[type=text]').attr('placeholder', 'Search');
  });
}
$(document).ready(function() {
  // Load Datatables and run plugin on tables 
  LoadDataTablesScripts(AllTables);
  // Add Drag-n-Drop feature
  WinMove();
  $("tr[data-href]").click(function() {
  window.location = this.dataset.href;
}).hover(function() {
    $(this).toggleClass('hover');
});
});


</script>

app/views/expenses/_new.html.erb
<%= render "layouts/ajaxify" %>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/_show.html.erb
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المصروفات</li>
      <li>بيانات المصروف</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>تفاصيل المصروف</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
          <%= form_for(@expense, html: {class: 'form-horizontal'}) do |f| %>
            <% if @expense.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

                <ul>
                <% @expense.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= label_tag 'date',  'التاريخ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'date', @expense.date_added, {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= label_tag 'employee',  'الموظف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= text_field_tag 'user_name', @expense.user_name, {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :name,  'وصف المصروفات', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :seller,  'المستحق', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :seller , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :price,  'المبلغ', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :price , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :e_type,  'النوع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.select :e_type, [['مصروفات عمومية', 0], ['مصروفات تشغيلية', 1]], {}, {class:"pull-right", style:"min-width:100%", disabled:true} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :payment_method,  'طريقة الدفع', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :payment_method, {class:"pull-right", disabled:true} %>
              </div>
            </div>

          </div>
          </div>
          <%= link_to 'تعديل', edit_expense_path(@expense)%>
          <%= link_to 'حذف', @expense, method: :delete, data: { confirm: 'هل أنت متأكد؟' } %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(DemoFormValidator);
  // Add drag-n-drop feature to boxes
  WinMove();
});
</script>