config/routes.rb
Rails.application.routes.draw do

  resources :productions

  match '/signin', :to => 'sessions#new', via: [:get]
  match '/signout', :to => 'sessions#destroy', via: [:get]
  match '/dashboard', to: 'dashboard#index', via: [:get]
  match '/stock', to: 'stock#index', via: [:get]
  match '/status', to: 'status#index', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:get]
  match '/diaries/treasury', to: 'diaries#treasury', via: [:post]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:get]
  match '/diaries/transactions', to: 'diaries#transactions', via: [:post]
  match '/diaries/stock', to: 'diaries#stock', via: [:get]
  match '/diaries/stock', to: 'diaries#stock', via: [:post]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:get]
  match '/diaries/diaries', to: 'diaries#diaries', via: [:post]
  match '/invoices', to: 'invoices#purchases', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:get]
  match '/wear_outs', to: 'ehlak_osool#index', via: [:post]
  match '/wear_outs/update', to: 'ehlak_osool#update', via: [:post]
  match '/income', to: 'income_menu#index', via: [:get]
  match '/income/:year', to: 'income_menu#index', via: [:get]
  match '/income/update', to: 'income_menu#update', via: [:patch]
  match '/financial_state', to: 'financial_state#index', via: [:get]
  match '/financial_state/:year', to: 'financial_state#index', via: [:get]
  match '/financial_state/update', to: 'financial_state#update', via: [:patch]
  match '/revision', to: 'revision#index', via: [:get]
  match '/revision/:year', to: 'revision#index', via: [:get]
  match '/revision/update', to: 'revision#update', via: [:patch]
  match '/clients/status', to: 'clients#status', via: [:post]
  match '/clients/:id', to: 'clients#show', via: [:post]
  match '/suppliers/:id', to: 'suppliers#show', via: [:post]
  match '/taxes', to: 'taxes#index', via: [:post]

  get '/dashboard/index'
  get '/clients/status'

  get 'dashboard/*a/*b', to: redirect('/%{a}/%{b}')
  get 'stock/index'
  match '/taxes', to: 'taxes#index', via: [:get]
  match '/taxes/:year', to: 'taxes#index', via: [:get]
  match '/taxes', to: 'taxes#index', via: [:post]

  get 'permission/production/:id', to: 'permission#production'
  get 'permission/product/:id', to: 'permission#product'
  get 'permission/material_stock/:id', to: 'permission#material_stock'
  get 'permission/material_expense/:id', to: 'permission#material_expense'
  get 'permission/material/:id1/:id2', to: 'permission#material'
  get 'permission/purchase/:id1/:id2', to: 'permission#purchase_with_invoice'
  get 'permission/purchase/:id', to: 'permission#purchase'
  get 'permission/expense/:id', to: 'permission#expense'
  
  get 'diaries/index', to: 'diaries#diaries'
  post 'diaries/index', to: 'diaries#diaries'

  get 'raw_materials/production'
  post 'raw_materials/permit'
  get 'raw_materials/permission'
  post 'materials/confirm'
  post 'purchases/confirm'

  get 'invoices/sales'
  get 'invoices/purchases'
  get 'permission/additions'
  get 'permission/subtractions'
  get 'permission/treasury'

  post 'expenses/confirm'
  get 'expenses/permission'
  get 'expenses/index'

  get 'purchases/invoice/:id', to: 'purchases#invoice'
  post 'materials/confirm'
  get 'materials/new_internal'
  get 'treasury/addtotreasury'
  get 'treasury/show'
  put 'treasury/update'

  get 'expense_payment_detail/:id', to: 'expense_payment_detail#edit'
  put 'expense_payment_detail/:id', to: 'expense_payment_detail#update'
  get 'purchase_payment_detail/:id', to: 'purchase_payment_detail#edit'
  put 'purchase_payment_detail/:id', to: 'purchase_payment_detail#update'
  get 'material_payment_detail/:id', to: 'material_payment_detail#edit'
  put 'material_payment_detail/:id', to: 'material_payment_detail#update'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users

  resources :treasury

  resources :suppliers

  resources :clients

  resources :purchases

  resources :expenses

  resources :products

  resources :materials
  resources :raw_materials
  resources :purchase_payment_detail
  resources :expense_payment_detail
  resources :material_payment_detail

   root 'sessions#new'

end

app/models/product.rb
class Product < ActiveRecord::Base

	before_save :validate

	private
		def validate
			self.deleted  ||= 0
		end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where.not(deleted: 1)
    super
    flash.discard(:notice)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    super
  end

  # GET /products/new
  def new
    @product = Product.new
    super
  end

  # GET /products/1/edit
  def edit
    super
  end

  # POST /products
  # POST /products.json
  def create
    if !validate_params(product_params) then
      redirect_to "/products/new", notice: 'تعذر إضافة المنتج. برجاء مراجعة المدخلات.'
    else
      @product = Product.new(product_params)
      @product.in_stock = @product.quantity
      respond_to do |format|
        if @product.save
          permission = AddProductPermission.create!({transaction_id: @product.id, quantity: @product.quantity})

          format.html { redirect_to "/permission/product/#{permission.id}" }
          format.json { render :show, status: :created, location: @product }
        else
          redirect_to "/products/new", notice: 'تعذر إضافة المنتج. برجاء مراجعة المدخلات.'
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'تم تعديل البيانات بنجاح.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    purchases = Purchase.where(["product_ids like ?", "%#{@product.id}%"])
    if purchases.empty?
      @product.destroy
    else
      @product.update(deleted: 1)
    end

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :unit, :quantity, :in_stock, :description)
    end

    def validate_params(params)
      if params[:name].present? && params[:unit].present? && params[:quantity].present? then
          return is_float?(params[:quantity]) && (params[:in_stock].blank? || is_float?(params[:in_stock]))
      end
      return nil
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_edit.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المنتجات</li>
      <li>تعديل.منتج</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>تعديل بيانات المنتج</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@product, html: {class: 'form-horizontal'}) do |f| %>
            <% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :name,  'اسم المنتج', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :description,  'الوصف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_area :description , {class:"form-control", placeholder:"الوصف"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :unit,  'الوحدة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :unit , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :in_stock,  'كمية المخزون', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :in_stock , {class:"form-control"}%>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2 pull-right">
                <%= f.submit "تعديل المنتج", class:"btn btn-primary btn-label-left" %>
              </div>
              <div class="col-sm-offset-1 col-sm-2 pull-right">
                <button type="cancel" class="btn btn-default btn-label-left">
                <span><i class="fa fa-clock-o txt-danger"></i></span>
                  إلغاء
                </button>
            </div>
          </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
function validator() {
    $('form').bootstrapValidator({
    message: 'برجاء مراجعة المدخل',
    fields: {
      'product[name]': {
        message: 'الاسم غير مقبول',
        validators: {
          notEmpty: {
            message: 'الاسم لا يمكن أن يكون فارغاً'
          },
          stringLength: {
            min: 3,
            max: 30,
            message: 'الاسم من 3 إلى 30 حرف'
          }
        }
      },
      'product[unit]': {
        validators: {
          notEmpty: {
            message: 'لابد من إدخال الوحدة'
          }
        }
      },
      'product[quantity]': {
        validators: {
          numeric: {
            message: 'أرقام فقط'
          }
        }
      },
      'product[price_per_unit]': {
        validators: {
          numeric: {
            message: 'أرقام فقط'
          }
        }
      },
      'product[in_stock]': {
        validators: {
          digits: {
            message: 'أرقام فقط'
          }
        }
      }
    }
  });
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(validator);
  // Add drag-n-drop feature to boxes
  WinMove();
  // $('button[type=cancel],select').attr('onclick', 'window.location.href = "/"; return false;')
});
</script>

app/views/products/_form.html.erb
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المنتجات</li>
      <li>تسجيل.منتج</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>إدخال بيانات منتج جديد</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@product, html: {class: 'form-horizontal'}) do |f| %>
            <% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :name,  'اسم المنتج', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", placeholder:"اسم المنتج", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"اسم المنتج"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :description,  'الوصف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_area :description , {class:"form-control", placeholder:"الوصف"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :unit,  'الوحدة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :unit , {class:"form-control", placeholder:"مثال: كجم", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"الوحدة"}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :quantity,  'الكمية', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :quantity , {class:"form-control", placeholder:"رقم", 'data-toggle' => "tooltip", 'data-placement' => "bottom", title:"رقم"}%>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-2 pull-right">
                <%= f.submit "تسجيل المنتج", class:"btn btn-primary btn-label-left" %>
              </div>
              <div class="col-sm-offset-1 col-sm-2 pull-right">
                <button type="cancel" class="btn btn-default btn-label-left">
                <span><i class="fa fa-clock-o txt-danger"></i></span>
                  إلغاء
                </button>
            </div>
          </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}

function validator() {
    $('#new_product').bootstrapValidator({
    message: 'برجاء مراجعة المدخل',
    fields: {
      'product[name]': {
        message: 'الاسم غير مقبول',
        validators: {
          notEmpty: {
            message: 'الاسم لا يمكن أن يكون فارغاً'
          },
          stringLength: {
            min: 3,
            max: 30,
            message: 'الاسم من 3 إلى 30 حرف'
          }
        }
      },
      'product[unit]': {
        validators: {
          notEmpty: {
            message: 'لابد من إدخال الوحدة'
          }
        }
      },
      'product[quantity]': {
        validators: {
          numeric: {
            message: 'أرقام فقط'
          }
        }
      },
      'product[price_per_unit]': {
        validators: {
          numeric: {
            message: 'أرقام فقط'
          }
        }
      }
    }
  });
}

$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(validator);
  // Add drag-n-drop feature to boxes
  WinMove();
  // $('button[type=cancel],select').attr('onclick', 'window.location.href = "/"; return false;')
});
</script>

app/views/products/_index.html.erb
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرسمية</li>
      <li>المنتجات</li>
      <li>عرض المنتجات</li>
    </ol>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-linux"></i>
          <span>عرض المنتجات</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content no-padding table-responsive">
        <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-2">
          <thead>
            <tr>
              <th>الاسم</th>
              <th>الوحدة</th>
              <th>الموجود بالمخزن</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr data-href="<%= product_path(product) %>">
                
                <td><%= product.name %></td>
                <td><%= product.unit %></td>
                <td><%= product.in_stock %></td>
              </tr>
            <% end %>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <th><label><input type="text" name="search_name" value="البحث بالاسم" class="search_init" /></label></th>
              <th><label><input type="text" name="search_unit" value="البحث بالوحدة" class="search_init" /></label></th>
              <th><label><input type="text" name="search_state" value="البحث بالموجود بالمخزن" class="search_init" /></label></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
  setupTables();
  LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
  $('select').select2();
  $('.dataTables_filter').each(function(){
    $(this).find('label input[type=text]').attr('placeholder', 'Search');
  });
}
$(document).ready(function() {
  // Load Datatables and run plugin on tables 
  LoadDataTablesScripts(AllTables);
  // Add Drag-n-Drop feature
  WinMove();
  $("tr[data-href]").click(function() {
  window.location = this.dataset.href;
}).hover(function() {
    $(this).toggleClass('hover');
});
});
</script>

app/views/products/_new.html.erb
<%= render "layouts/ajaxify" %>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/_show.html.erb
<%= render "layouts/ajaxify" %>
<%= render "layouts/ajaxify" %>
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li>الصفحة الرئيسية</li>
      <li>المنتجات</li>
      <li>عرض.منتج</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-search"></i>
          <span>عرض بيانات المنتج</span>
        </div>

        <div class="no-move"></div>
      </div>
      <div class="box-content">
        <% if notice.present? %>
        <h3 class="alert alert-danger"><%= notice%></h3>
        <%end%>
          <%= form_for(@product, html: {class: 'form-horizontal'}) do |f| %>
            <% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :name,  'اسم المنتج', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :name , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :description,  'الوصف', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_area :description , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :unit,  'الوحدة', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :unit , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :in_stock,  'كمية المخزون', {class:"col-sm-2 control-label pull-right"}%>
              <div class="col-sm-4 pull-right">
                <%= f.text_field :in_stock , {class:"form-control", disabled:true}%>
              </div>
            </div>

            <%= link_to 'تعديل', edit_product_path(@product) %>
            <%= link_to 'حذف', @product, method: :delete, data: { confirm: 'هل أنت متأكد؟' } %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
  $('#s2_with_tag').select2({placeholder: "Select OS"});
  $('#s2_country').select2();
}
// Run timepicker
function DemoTimePicker(){
  $('#input_time').timepicker({setDate: new Date()});
}
$(document).ready(function() {
  // Create Wysiwig editor for textare
  TinyMCEStart('#wysiwig_simple', null);
  TinyMCEStart('#wysiwig_full', 'extreme');
  // Add slider for change test input length
  FormLayoutExampleInputLength($( ".slider-style" ));
  // Initialize datepicker
  $('#input_date').datepicker({setDate: new Date()});
  // Load Timepicker plugin
  LoadTimePickerScript(DemoTimePicker);
  // Add tooltip to form-controls
  $('.form-control').tooltip();
  LoadSelect2Script(DemoSelect2);
  // Load example of form validation
  LoadBootstrapValidatorScript(DemoFormValidator);
  // Add drag-n-drop feature to boxes
  WinMove();
});
</script>